import type { AdminOfficer, Organizer } from '../types/content';

// Officers of the organization. They sit in the vertical admin panel on the
// left of the Team page, above the Expo's own chain of responsibility.
export const adminOfficers: AdminOfficer[] = [
  {
    id: 'ava-thompson',
    name: 'Ava Thompson',
    role: 'President',
    affiliation: "Yale '26, Political Science",
    headshotUrl: '/headshots/ava-thompson.svg',
    email: 'president@yaleimpactexpo.org',
  },
  {
    id: 'marcus-chen',
    name: 'Marcus Chen',
    role: 'Vice President',
    affiliation: "Yale '27, Economics",
    headshotUrl: '/headshots/marcus-chen.svg',
    email: 'vicepresident@yaleimpactexpo.org',
  },
  {
    id: 'elena-petrova',
    name: 'Elena Petrova',
    role: 'Chief Financial Officer',
    affiliation: "Yale '28, Applied Mathematics",
    headshotUrl: '/headshots/elena-petrova.svg',
    email: 'finance@yaleimpactexpo.org',
  },
];

// The Expo team, in three ranks: the chair, the executive council that reports
// to the chair, and the leads who run the day-to-day work.
export const organizers: Organizer[] = [
  {
    id: 'jamal-whitfield',
    name: 'Jamal Whitfield',
    role: 'Chairman',
    rank: 'chair',
    affiliation: "Yale '26, History",
    headshotUrl: '/headshots/jamal-whitfield.svg',
    bio: 'Jamal sets the direction of the Expo and answers for it. He chairs the executive council, holds the partner relationships, and keeps the programme accountable to the students it is built for.',
    linkedinUrl: 'https://www.linkedin.com/in/jamal-whitfield',
    email: 'chair@yaleimpactexpo.org',
  },
  {
    id: 'priya-nair',
    name: 'Priya Nair',
    role: 'Executive Director, Programs',
    rank: 'executive',
    affiliation: "Yale '27, Global Affairs",
    headshotUrl: '/headshots/priya-nair.svg',
    bio: 'Priya runs the semester: team formation, track structure, mentorship matching, and the judging rubric that keeps every project held to the same standard.',
    email: 'programs@yaleimpactexpo.org',
  },
  {
    id: 'omar-haddad',
    name: 'Omar Haddad',
    role: 'Executive Director, Partnerships',
    rank: 'executive',
    affiliation: "Yale '28, Economics",
    headshotUrl: '/headshots/omar-haddad.svg',
    bio: 'Omar builds the partner roster across all nine domains and protects the principle that no sponsor owns a track and no partner is priced out of the room.',
    linkedinUrl: 'https://www.linkedin.com/in/omar-haddad',
    email: 'partnerships@yaleimpactexpo.org',
  },
  {
    id: 'grace-lin',
    name: 'Grace Lin',
    role: 'Executive Director, Technology',
    rank: 'executive',
    affiliation: "Yale '26, Computer Science",
    headshotUrl: '/headshots/grace-lin.svg',
    bio: 'Grace leads the platform, the submission pipeline, and the tooling partnerships that put cloud credits and engineering help in the hands of every team that needs them.',
    linkedinUrl: 'https://www.linkedin.com/in/grace-lin',
    email: 'tech@yaleimpactexpo.org',
  },
  {
    id: 'lucia-ferreira',
    name: 'Lucia Ferreira',
    role: 'Executive Director, Communications',
    rank: 'executive',
    affiliation: "Yale '27, English",
    headshotUrl: '/headshots/lucia-ferreira.svg',
    bio: 'Lucia edits everything the Expo publishes and makes sure student work reaches the readers, reporters, and practitioners who can carry it further.',
    email: 'press@yaleimpactexpo.org',
  },
  {
    id: 'diego-alvarez',
    name: 'Diego Alvarez',
    role: 'Design Lead',
    rank: 'team',
    affiliation: "Yale '28, Computer Science",
    headshotUrl: '/headshots/diego-alvarez.svg',
    bio: 'Diego designs the Expo identity, the track banners, and the presentation materials teams take on stage.',
    email: 'design@yaleimpactexpo.org',
  },
  {
    id: 'sofia-kim',
    name: 'Sofia Kim',
    role: 'Outreach Lead',
    rank: 'team',
    affiliation: "Yale '27, Cognitive Science",
    headshotUrl: '/headshots/sofia-kim.svg',
    bio: 'Sofia recruits across every school and department, with a standing brief to reach students who have no existing route into labs, firms, or funding.',
    email: 'outreach@yaleimpactexpo.org',
  },
  {
    id: 'noah-fitzgerald',
    name: 'Noah Fitzgerald',
    role: 'Community Lead',
    rank: 'team',
    affiliation: "Yale '27, Sociology",
    headshotUrl: '/headshots/noah-fitzgerald.svg',
    bio: 'Noah is the link to New Haven: he brings community organizations to the table early and keeps local projects answerable to local needs.',
    email: 'community@yaleimpactexpo.org',
  },
  {
    id: 'ben-okafor',
    name: 'Ben Okafor',
    role: 'Operations Lead',
    rank: 'team',
    affiliation: "Yale '26, Environmental Studies",
    headshotUrl: '/headshots/ben-okafor.svg',
    bio: 'Ben runs the weekend itself — venues, volunteers, judging logistics, and the hundred small things that make a large event feel calm.',
    email: 'operations@yaleimpactexpo.org',
  },
];
