import type { Organizer } from '../types/content';

// Placeholder organizers. The team replaces this list with the real roster later.
export const organizers: Organizer[] = [
  {
    id: 'ava-thompson',
    name: 'Ava Thompson',
    role: 'President',
    affiliation: "Yale '26, Political Science",
    headshotUrl: '/headshots/ava-thompson.svg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    linkedinUrl: 'https://www.linkedin.com/in/ava-thompson',
    email: 'ava@yaleimpactexpo.org',
  },
  {
    id: 'marcus-chen',
    name: 'Marcus Chen',
    role: 'Vice President of Sponsorship',
    affiliation: "Yale '27, Economics",
    headshotUrl: '/headshots/marcus-chen.svg',
    bio: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris. Duis aute irure dolor in reprehenderit in voluptate.',
    linkedinUrl: 'https://www.linkedin.com/in/marcus-chen',
    email: 'marcus@yaleimpactexpo.org',
  },
  {
    id: 'priya-nair',
    name: 'Priya Nair',
    role: 'Logistics Lead',
    affiliation: "Yale '27, Global Affairs",
    headshotUrl: '/headshots/priya-nair.svg',
    bio: 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    email: 'priya@yaleimpactexpo.org',
  },
  {
    id: 'diego-alvarez',
    name: 'Diego Alvarez',
    role: 'Design Lead',
    affiliation: "Yale '28, Computer Science",
    headshotUrl: '/headshots/diego-alvarez.svg',
    bio: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium. Totam rem aperiam eaque ipsa quae ab illo inventore veritatis.',
    email: 'diego@yaleimpactexpo.org',
  },
  {
    id: 'sofia-kim',
    name: 'Sofia Kim',
    role: 'Marketing Lead',
    affiliation: "Yale '27, Cognitive Science",
    headshotUrl: '/headshots/sofia-kim.svg',
    bio: 'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit. Sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
    linkedinUrl: 'https://www.linkedin.com/in/sofia-kim',
    email: 'sofia@yaleimpactexpo.org',
  },
  {
    id: 'jamal-whitfield',
    name: 'Jamal Whitfield',
    role: 'Speaker Coordinator',
    affiliation: "Yale '26, History",
    headshotUrl: '/headshots/jamal-whitfield.svg',
    bio: 'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet consectetur adipisci velit. Sed quia non numquam eius modi tempora incidunt.',
    email: 'jamal@yaleimpactexpo.org',
  },
  {
    id: 'elena-petrova',
    name: 'Elena Petrova',
    role: 'Finance Lead',
    affiliation: "Yale '28, Applied Mathematics",
    headshotUrl: '/headshots/elena-petrova.svg',
    bio: 'Ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam quis nostrum exercitationem ullam corporis suscipit.',
    email: 'elena@yaleimpactexpo.org',
  },
  {
    id: 'noah-fitzgerald',
    name: 'Noah Fitzgerald',
    role: 'Volunteer Coordinator',
    affiliation: "Yale '27, Sociology",
    headshotUrl: '/headshots/noah-fitzgerald.svg',
    bio: 'Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.',
    email: 'noah@yaleimpactexpo.org',
  },
  {
    id: 'grace-lin',
    name: 'Grace Lin',
    role: 'Technology Lead',
    affiliation: "Yale '26, Computer Science",
    headshotUrl: '/headshots/grace-lin.svg',
    bio: 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti.',
    linkedinUrl: 'https://www.linkedin.com/in/grace-lin',
    email: 'grace@yaleimpactexpo.org',
  },
  {
    id: 'omar-haddad',
    name: 'Omar Haddad',
    role: 'Partnerships Lead',
    affiliation: "Yale '28, Economics",
    headshotUrl: '/headshots/omar-haddad.svg',
    bio: 'Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit.',
    email: 'omar@yaleimpactexpo.org',
  },
  {
    id: 'lucia-ferreira',
    name: 'Lucia Ferreira',
    role: 'Communications Lead',
    affiliation: "Yale '27, English",
    headshotUrl: '/headshots/lucia-ferreira.svg',
    bio: 'Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet. Ut et voluptates repudiandae sint et molestiae non recusandae.',
    linkedinUrl: 'https://www.linkedin.com/in/lucia-ferreira',
    email: 'lucia@yaleimpactexpo.org',
  },
  {
    id: 'ben-okafor',
    name: 'Ben Okafor',
    role: 'Operations Lead',
    affiliation: "Yale '26, Environmental Studies",
    headshotUrl: '/headshots/ben-okafor.svg',
    bio: 'Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.',
    email: 'ben@yaleimpactexpo.org',
  },
];
