import type { Sponsor } from '../types/content';

// Placeholder sponsors. The team replaces this list with real sponsors later.
export const sponsors: Sponsor[] = [
  {
    id: 'meridian-policy-institute',
    name: 'Meridian Policy Institute',
    sector: 'nonprofit',
    tier: 'lead',
    logoUrl: '/logos/meridian-policy-institute.svg',
    websiteUrl: 'https://meridian-policy-institute.example',
    blurb:
      'Meridian Policy Institute studies public policy outcomes across housing, health, and education. The team partners with universities on applied research.',
    featured: true,
  },
  {
    id: 'beacon-civic-trust',
    name: 'Beacon Civic Trust',
    sector: 'nonprofit',
    tier: 'partner',
    logoUrl: '/logos/beacon-civic-trust.svg',
    websiteUrl: 'https://beacon-civic-trust.example',
    blurb: 'Beacon Civic Trust funds community programs in small and mid-size cities.',
    featured: false,
  },
  {
    id: 'harborlight-foundation',
    name: 'Harborlight Foundation',
    sector: 'nonprofit',
    tier: 'supporting',
    logoUrl: '/logos/harborlight-foundation.svg',
    blurb: 'Harborlight Foundation gives grants to nonprofits that serve coastal communities.',
    featured: false,
  },
  {
    id: 'common-ground-alliance',
    name: 'Common Ground Alliance',
    sector: 'nonprofit',
    tier: 'supporting',
    logoUrl: '/logos/common-ground-alliance.svg',
    blurb: 'Common Ground Alliance builds coalitions between local nonprofits and city government.',
    featured: false,
  },
  {
    id: 'bureau-of-applied-analytics',
    name: 'Bureau of Applied Analytics',
    sector: 'government',
    tier: 'lead',
    logoUrl: '/logos/bureau-of-applied-analytics.svg',
    websiteUrl: 'https://bureau-of-applied-analytics.example',
    blurb:
      'The Bureau of Applied Analytics gives data tools to public agencies. The team works on transportation, health, and safety programs.',
    featured: true,
  },
  {
    id: 'office-of-regional-innovation',
    name: 'Office of Regional Innovation',
    sector: 'government',
    tier: 'partner',
    logoUrl: '/logos/office-of-regional-innovation.svg',
    websiteUrl: 'https://office-of-regional-innovation.example',
    blurb: 'The Office of Regional Innovation runs pilot programs for state and local government.',
    featured: false,
  },
  {
    id: 'civic-systems-directorate',
    name: 'Civic Systems Directorate',
    sector: 'government',
    tier: 'supporting',
    logoUrl: '/logos/civic-systems-directorate.svg',
    blurb: 'The Civic Systems Directorate manages digital services for city residents.',
    featured: false,
  },
  {
    id: 'national-resilience-council',
    name: 'National Resilience Council',
    sector: 'government',
    tier: 'supporting',
    logoUrl: '/logos/national-resilience-council.svg',
    blurb: 'The National Resilience Council plans climate and disaster response across regions.',
    featured: false,
  },
  {
    id: 'ironclad-defense-systems',
    name: 'Ironclad Defense Systems',
    sector: 'defense',
    tier: 'lead',
    logoUrl: '/logos/ironclad-defense-systems.svg',
    websiteUrl: 'https://ironclad-defense-systems.example',
    blurb:
      'Ironclad Defense Systems builds secure communication hardware for the field. The team hires engineers straight from university programs.',
    featured: true,
  },
  {
    id: 'sentinel-dynamics',
    name: 'Sentinel Dynamics',
    sector: 'defense',
    tier: 'partner',
    logoUrl: '/logos/sentinel-dynamics.svg',
    websiteUrl: 'https://sentinel-dynamics.example',
    blurb: 'Sentinel Dynamics designs sensor systems for defense and safety applications.',
    featured: true,
  },
  {
    id: 'vantage-point-technologies',
    name: 'Vantage Point Technologies',
    sector: 'defense',
    tier: 'supporting',
    logoUrl: '/logos/vantage-point-technologies.svg',
    blurb: 'Vantage Point Technologies builds simulation software for training programs.',
    featured: false,
  },
  {
    id: 'northgate-defense-partners',
    name: 'Northgate Defense Partners',
    sector: 'defense',
    tier: 'supporting',
    logoUrl: '/logos/northgate-defense-partners.svg',
    blurb: 'Northgate Defense Partners advises government clients on program strategy.',
    featured: false,
  },
  {
    id: 'cascade-ai-labs',
    name: 'Cascade AI Labs',
    sector: 'ai-research',
    tier: 'lead',
    logoUrl: '/logos/cascade-ai-labs.svg',
    websiteUrl: 'https://cascade-ai-labs.example',
    blurb:
      'Cascade AI Labs builds machine learning models for public sector partners. The team publishes open research each year.',
    featured: true,
  },
  {
    id: 'latticework-research',
    name: 'Latticework Research',
    sector: 'ai-research',
    tier: 'partner',
    logoUrl: '/logos/latticework-research.svg',
    websiteUrl: 'https://latticework-research.example',
    blurb: 'Latticework Research studies the safety and reliability of large language models.',
    featured: true,
  },
  {
    id: 'openfield-ai-institute',
    name: 'Openfield AI Institute',
    sector: 'ai-research',
    tier: 'supporting',
    logoUrl: '/logos/openfield-ai-institute.svg',
    blurb: 'Openfield AI Institute runs open workshops on applied machine learning.',
    featured: false,
  },
  {
    id: 'recurrent-systems-group',
    name: 'Recurrent Systems Group',
    sector: 'ai-research',
    tier: 'supporting',
    logoUrl: '/logos/recurrent-systems-group.svg',
    blurb: 'Recurrent Systems Group builds forecasting tools for supply chains.',
    featured: false,
  },
  {
    id: 'whitfield-university-research-office',
    name: 'Whitfield University Research Office',
    sector: 'academia',
    tier: 'lead',
    logoUrl: '/logos/whitfield-university-research-office.svg',
    websiteUrl: 'https://whitfield-university-research-office.example',
    blurb:
      'The Whitfield University Research Office funds student research across every department. The office runs a summer fellowship each year.',
    featured: true,
  },
  {
    id: 'elm-street-scholars-program',
    name: 'Elm Street Scholars Program',
    sector: 'academia',
    tier: 'partner',
    logoUrl: '/logos/elm-street-scholars-program.svg',
    websiteUrl: 'https://elm-street-scholars-program.example',
    blurb: 'The Elm Street Scholars Program gives first generation students access to research mentors.',
    featured: false,
  },
  {
    id: 'bridgeview-academic-consortium',
    name: 'Bridgeview Academic Consortium',
    sector: 'academia',
    tier: 'supporting',
    logoUrl: '/logos/bridgeview-academic-consortium.svg',
    blurb: 'The Bridgeview Academic Consortium links small colleges on shared research grants.',
    featured: false,
  },
  {
    id: 'lakeside-institute-for-data-science',
    name: 'Lakeside Institute for Data Science',
    sector: 'academia',
    tier: 'supporting',
    logoUrl: '/logos/lakeside-institute-for-data-science.svg',
    blurb: 'The Lakeside Institute for Data Science trains graduate students in applied statistics.',
    featured: false,
  },
  {
    id: 'solstice-technologies',
    name: 'Solstice Technologies',
    sector: 'industry',
    tier: 'lead',
    logoUrl: '/logos/solstice-technologies.svg',
    websiteUrl: 'https://solstice-technologies.example',
    blurb:
      'Solstice Technologies builds renewable energy software for utility companies. The team is hiring across engineering and design.',
    featured: false,
  },
  {
    id: 'ferrovia-logistics',
    name: 'Ferrovia Logistics',
    sector: 'industry',
    tier: 'partner',
    logoUrl: '/logos/ferrovia-logistics.svg',
    websiteUrl: 'https://ferrovia-logistics.example',
    blurb: 'Ferrovia Logistics builds routing software for freight and rail companies.',
    featured: false,
  },
  {
    id: 'brightline-consulting-group',
    name: 'Brightline Consulting Group',
    sector: 'industry',
    tier: 'supporting',
    logoUrl: '/logos/brightline-consulting-group.svg',
    blurb: 'Brightline Consulting Group advises growing companies on strategy and operations.',
    featured: false,
  },
  {
    id: 'anchorpoint-analytics',
    name: 'Anchorpoint Analytics',
    sector: 'industry',
    tier: 'supporting',
    logoUrl: '/logos/anchorpoint-analytics.svg',
    blurb: 'Anchorpoint Analytics builds dashboards for retail and logistics teams.',
    featured: true,
  },
];
